"""Business services, re-exported so routers keep the old services.* call sites."""

from app.services.audit import list_audit_logs, list_call_logs
from app.services.common import mask_key
from app.services.eval import list_eval_runs, run_question_eval, run_score_eval
from app.services.interview import (
    answer_interview,
    current_question,
    abandon_interview,
    build_report,
    delete_interview,
    end_interview,
    finish_interview,
    get_interview,
    list_interviews,
    prepare_interview,
    resume_or_start,
    schedule_report,
    start_interview,
)
from app.services.knowledge import (
    accept_material,
    delete_material,
    enqueue_material_id,
    get_material,
    list_materials,
    pending_material_ids,
    recall,
    start_material_worker,
)
from app.services.overview import admin_overview
from app.services.providers import (
    create_provider,
    delete_provider,
    list_providers,
    list_roles,
    ping_provider,
    probe_models,
    seed_providers,
    update_provider,
    update_role,
)
from app.services.session import (
    begin_chat,
    chat_stream_mode,
    clear_session,
    complete_chat_turn,
    create_session,
    delete_session,
    finish_chat,
    get_session,
    iter_turn_parts,
    prepare_chat_file,
    list_sessions,
    send_chat,
)

__all__ = [
    "accept_material",
    "admin_overview",
    "answer_interview",
    "begin_chat",
    "chat_stream_mode",
    "clear_session",
    "complete_chat_turn",
    "create_provider",
    "create_session",
    "current_question",
    "delete_interview",
    "delete_material",
    "delete_provider",
    "delete_session",
    "end_interview",
    "enqueue_material_id",
    "finish_chat",
    "get_interview",
    "get_material",
    "get_session",
    "iter_turn_parts",
    "prepare_chat_file",
    "list_audit_logs",
    "list_call_logs",
    "list_eval_runs",
    "list_interviews",
    "prepare_interview",
    "list_materials",
    "list_providers",
    "list_roles",
    "list_sessions",
    "mask_key",
    "pending_material_ids",
    "ping_provider",
    "probe_models",
    "recall",
    "resume_or_start",
    "run_question_eval",
    "run_score_eval",
    "schedule_report",
    "seed_providers",
    "send_chat",
    "start_interview",
    "start_material_worker",
    "update_provider",
    "update_role",
]
